# Generated by Django 3.0.6 on 2020-06-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('clas', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('place_detail', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=25)),
                ('no_student', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
