# Generated by Django 3.0.6 on 2020-06-10 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=25)),
                ('university', models.CharField(max_length=25)),
                ('college', models.CharField(max_length=25)),
                ('school', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('number', models.IntegerField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
