# Generated by Django 3.0.6 on 2020-06-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0004_auto_20200610_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
